--- 
${nginx_server_info}: 
  hosts: ${nginx_server_ip}
  vars: 
    ansible_ssh_private_key_file: ${ssh_keyfile}
    ansible_ssh_user: ${ssh_user}
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    
${ab_server_info}: 
  hosts: ${apache_ab_server_ip}
  vars: 
    ansible_ssh_private_key_file: ${ssh_keyfile}
    ansible_ssh_user: ${ssh_user}
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"